config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('results', views.ResultsView.as_view(), name='results')
]

main/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms

class PaizaAuthenticationForm(forms.Form):
    email = forms.EmailField(max_length=100, label='email', required=True)
    password = forms.CharField(max_length=100, label='password', widget=forms.PasswordInput(), required=True)

main/views.py
from django.views import generic

import requests
from .forms import PaizaAuthenticationForm
from .module.scraper import login, get_results_data, get_user_name


class IndexView(generic.TemplateView):
    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        form = PaizaAuthenticationForm
        context = super().get_context_data(**kwargs)
        context['form'] = form
        return context

class ResultsView(generic.ListView):
    template_name = 'main/results.html'
    context_object_name = 'data'

    # def dispatch(self, request, *args, **kwargs):
    #     print('========dispatch======')
    #     self.is_logged_in = False
    #     return super(ResultsView, self).dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form_value = {
            'email': self.request.POST.get('email', default=None),
            'password': self.request.POST.get('password', default=None)
        }
        request.session['form_value'] = form_value

        self.request.GET = self.request.GET.copy()
        self.request.GET.clear()

        return self.get(request, *args, **kwargs)

    def get_queryset(self):
        if 'form_value' in self.request.session:
            form_value = self.request.session['form_value']
            email = form_value['email']
            password = form_value['password']

            if login(email, password):
                # self.is_logged_in = True
                queryset = {
                    'user_name': get_user_name(),
                    'results': get_results_data()
                }
                return queryset
            else:
                return None

templates/common/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/main/index.html
{% extends 'common/base.html' %}


{% block content %}

<h3>Enter your paiza credentials</h3>
{% if form %}
<form action="{% url 'main:results' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">submit</button>
</form>
{% endif %}


{% endblock %}

templates/main/results.html
{% extends 'common/base.html' %}
{% block content %}


<h3>List of results for {{ data.user_name }}</h3>
<section class="section">
    <table class="table is-hoverable">
        <thead>
            <tr>
                <th class="sort" data-sort="no">No.</th>
                <th class="sort" data-sort="ttl">Title</th>
                <th class="sort" data-sort="time">Firsr Answer Time</th>
                <th class="sort" data-sort="details">Details</th>
            </tr>
        </thead>
        <tbody class="list">
            {% for result in data.results %}
            <tr>
                <td class="no">{{ result.prob_num }}</td>
                <td class="ttl">{{ result.prob_name }}</td>
                <td class="time">{{ result.answer_time }}</td>
                <td class="details" style="display:flex; flex-wrap:wrap;">
                    {% for detail in result.details %}
                    <div class="card" style="margin-right:4px; margin-bottom:4px">
                        <div style="margin:4px">
                            <p>{{ detail.date }}</p>
                            <p>{{ detail.langage }}</p>
                            <p>{{ detail.score }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</section>

{% endblock %}